/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/001-build-self-gitrepo-server': RouteRecordInfo<
      '/posts/001-build-self-gitrepo-server',
      '/posts/001-build-self-gitrepo-server',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/002-blog-deploy': RouteRecordInfo<
      '/posts/002-blog-deploy',
      '/posts/002-blog-deploy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/003-qq-bot-brief-introduce': RouteRecordInfo<
      '/posts/003-qq-bot-brief-introduce',
      '/posts/003-qq-bot-brief-introduce',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/004-emotions-in-0325': RouteRecordInfo<
      '/posts/004-emotions-in-0325',
      '/posts/004-emotions-in-0325',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/005-deploy-blog-by-nginx-docker': RouteRecordInfo<
      '/posts/005-deploy-blog-by-nginx-docker',
      '/posts/005-deploy-blog-by-nginx-docker',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/006-Jackson-deserializes-auto-adapt-subclasses': RouteRecordInfo<
      '/posts/006-Jackson-deserializes-auto-adapt-subclasses',
      '/posts/006-Jackson-deserializes-auto-adapt-subclasses',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/007-your-own-email-server': RouteRecordInfo<
      '/posts/007-your-own-email-server',
      '/posts/007-your-own-email-server',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/008-one-bot-message-persistence': RouteRecordInfo<
      '/posts/008-one-bot-message-persistence',
      '/posts/008-one-bot-message-persistence',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/009-redis-database-consistance': RouteRecordInfo<
      '/posts/009-redis-database-consistance',
      '/posts/009-redis-database-consistance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/010-refresh-certificates': RouteRecordInfo<
      '/posts/010-refresh-certificates',
      '/posts/010-refresh-certificates',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/011-michangsheng-lianqikaiju': RouteRecordInfo<
      '/posts/011-michangsheng-lianqikaiju',
      '/posts/011-michangsheng-lianqikaiju',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/012-jvm-classload': RouteRecordInfo<
      '/posts/012-jvm-classload',
      '/posts/012-jvm-classload',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/013-jvm-memory-model': RouteRecordInfo<
      '/posts/013-jvm-memory-model',
      '/posts/013-jvm-memory-model',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/014-michangsheng-bepinex-mod-dev': RouteRecordInfo<
      '/posts/014-michangsheng-bepinex-mod-dev',
      '/posts/014-michangsheng-bepinex-mod-dev',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/015-design-pattern': RouteRecordInfo<
      '/posts/015-design-pattern',
      '/posts/015-design-pattern',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/016-base-multithreading': RouteRecordInfo<
      '/posts/016-base-multithreading',
      '/posts/016-base-multithreading',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/017-java-lock': RouteRecordInfo<
      '/posts/017-java-lock',
      '/posts/017-java-lock',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/018-simple-clicker': RouteRecordInfo<
      '/posts/018-simple-clicker',
      '/posts/018-simple-clicker',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/019-zookeeper-overall-learn': RouteRecordInfo<
      '/posts/019-zookeeper-overall-learn',
      '/posts/019-zookeeper-overall-learn',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/020-zookeeper-apply': RouteRecordInfo<
      '/posts/020-zookeeper-apply',
      '/posts/020-zookeeper-apply',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/021-rpc-and-dubbo': RouteRecordInfo<
      '/posts/021-rpc-and-dubbo',
      '/posts/021-rpc-and-dubbo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/022-new-bot-design': RouteRecordInfo<
      '/posts/022-new-bot-design',
      '/posts/022-new-bot-design',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/023-maimai-deploy-note': RouteRecordInfo<
      '/posts/023-maimai-deploy-note',
      '/posts/023-maimai-deploy-note',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/024-jackson-polymorphic-subclass-auto-deserialize': RouteRecordInfo<
      '/posts/024-jackson-polymorphic-subclass-auto-deserialize',
      '/posts/024-jackson-polymorphic-subclass-auto-deserialize',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/025-java-appp-plugin-design': RouteRecordInfo<
      '/posts/025-java-appp-plugin-design',
      '/posts/025-java-appp-plugin-design',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/026-websocket-client-encapsulation': RouteRecordInfo<
      '/posts/026-websocket-client-encapsulation',
      '/posts/026-websocket-client-encapsulation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/027-yuni-deploy': RouteRecordInfo<
      '/posts/027-yuni-deploy',
      '/posts/027-yuni-deploy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/028-rdp-by-frp': RouteRecordInfo<
      '/posts/028-rdp-by-frp',
      '/posts/028-rdp-by-frp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/029-yuni-doc': RouteRecordInfo<
      '/posts/029-yuni-doc',
      '/posts/029-yuni-doc',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.26.12_vue@3.5.22_typescript@5.8.2_/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy@0.26.12_@babel+parse_27f15f176c0fa93d9a7d96b21c9ee04e/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.26.12_vue@3.5.22_typescript@5.8.2_/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.26.12_vue@3.5.22_typescript@5.8.2_/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/001-build-self-gitrepo-server.md': {
      routes:
        | '/posts/001-build-self-gitrepo-server'
      views:
        | never
    }
    'pages/posts/002-blog-deploy.md': {
      routes:
        | '/posts/002-blog-deploy'
      views:
        | never
    }
    'pages/posts/003-qq-bot-brief-introduce.md': {
      routes:
        | '/posts/003-qq-bot-brief-introduce'
      views:
        | never
    }
    'pages/posts/004-emotions-in-0325.md': {
      routes:
        | '/posts/004-emotions-in-0325'
      views:
        | never
    }
    'pages/posts/005-deploy-blog-by-nginx-docker.md': {
      routes:
        | '/posts/005-deploy-blog-by-nginx-docker'
      views:
        | never
    }
    'pages/posts/006-Jackson-deserializes-auto-adapt-subclasses.md': {
      routes:
        | '/posts/006-Jackson-deserializes-auto-adapt-subclasses'
      views:
        | never
    }
    'pages/posts/007-your-own-email-server.md': {
      routes:
        | '/posts/007-your-own-email-server'
      views:
        | never
    }
    'pages/posts/008-one-bot-message-persistence.md': {
      routes:
        | '/posts/008-one-bot-message-persistence'
      views:
        | never
    }
    'pages/posts/009-redis-database-consistance.md': {
      routes:
        | '/posts/009-redis-database-consistance'
      views:
        | never
    }
    'pages/posts/010-refresh-certificates.md': {
      routes:
        | '/posts/010-refresh-certificates'
      views:
        | never
    }
    'pages/posts/011-michangsheng-lianqikaiju.md': {
      routes:
        | '/posts/011-michangsheng-lianqikaiju'
      views:
        | never
    }
    'pages/posts/012-jvm-classload.md': {
      routes:
        | '/posts/012-jvm-classload'
      views:
        | never
    }
    'pages/posts/013-jvm-memory-model.md': {
      routes:
        | '/posts/013-jvm-memory-model'
      views:
        | never
    }
    'pages/posts/014-michangsheng-bepinex-mod-dev.md': {
      routes:
        | '/posts/014-michangsheng-bepinex-mod-dev'
      views:
        | never
    }
    'pages/posts/015-design-pattern.md': {
      routes:
        | '/posts/015-design-pattern'
      views:
        | never
    }
    'pages/posts/016-base-multithreading.md': {
      routes:
        | '/posts/016-base-multithreading'
      views:
        | never
    }
    'pages/posts/017-java-lock.md': {
      routes:
        | '/posts/017-java-lock'
      views:
        | never
    }
    'pages/posts/018-simple-clicker.md': {
      routes:
        | '/posts/018-simple-clicker'
      views:
        | never
    }
    'pages/posts/019-zookeeper-overall-learn.md': {
      routes:
        | '/posts/019-zookeeper-overall-learn'
      views:
        | never
    }
    'pages/posts/020-zookeeper-apply.md': {
      routes:
        | '/posts/020-zookeeper-apply'
      views:
        | never
    }
    'pages/posts/021-rpc-and-dubbo.md': {
      routes:
        | '/posts/021-rpc-and-dubbo'
      views:
        | never
    }
    'pages/posts/022-new-bot-design.md': {
      routes:
        | '/posts/022-new-bot-design'
      views:
        | never
    }
    'pages/posts/023-maimai-deploy-note.md': {
      routes:
        | '/posts/023-maimai-deploy-note'
      views:
        | never
    }
    'pages/posts/024-jackson-polymorphic-subclass-auto-deserialize.md': {
      routes:
        | '/posts/024-jackson-polymorphic-subclass-auto-deserialize'
      views:
        | never
    }
    'pages/posts/025-java-appp-plugin-design.md': {
      routes:
        | '/posts/025-java-appp-plugin-design'
      views:
        | never
    }
    'pages/posts/026-websocket-client-encapsulation.md': {
      routes:
        | '/posts/026-websocket-client-encapsulation'
      views:
        | never
    }
    'pages/posts/027-yuni-deploy.md': {
      routes:
        | '/posts/027-yuni-deploy'
      views:
        | never
    }
    'pages/posts/028-rdp-by-frp.md': {
      routes:
        | '/posts/028-rdp-by-frp'
      views:
        | never
    }
    'pages/posts/029-yuni-doc.md': {
      routes:
        | '/posts/029-yuni-doc'
      views:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
